// <auto-generated />
namespace EDAPacman.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class public_layout_and_player : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(public_layout_and_player));
        
        string IMigrationMetadata.Id
        {
            get { return "201505010129254_public_layout_and_player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
